[tool.isort]
    profile = 'black'
    line_length = 99
    combine_as_imports = true
    extra_standard_library = ['typing_extensions']

[tool.black]
    line-length = 99
    target-version = ['py38']
    include = '\.pyi?$'

[tool.pyright]
    useLibraryCodeForTypes = true
#   typeCheckingMode = 'strict'
    reportMissingTypeStubs = false
