name: pull

on:
  pull_request:
    branches:
      - master

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: make installreqs
      - name: Lint with Flake8
        run: make lint
      - name: Stylecheck with black, etc.
        run: make stylecheck
